backup:
    enabled: true
    image: 
        repository: elastic-backup
        tag: "1.0"
        pullPolicy: Never
    schedule: '0 * * * *'
    nfs:
        ip: 10.1.4.164
        path: /
    encryption:
        enabled: false
        encryptionKeySecret: encryption-key-secret
        pathToEncrypt: indices
    elastic:
        host: elasticsearch
        port: 9200
        repo: elastic
restore:
    enabled: false